language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls    
script:
  - pytest
  - coverage run -m pytest tests/
after_success:
  - coveralls
